spring.application.name=WebApp_Slack_Clone




spring.datasource.username=root
spring.datasource.password=Pankaj@4321
spring.datasource.url=jdbc:mysql://localhost:3306/slack

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true