spring:
  application:
    name: MS-Greet-api-1
  boot:
    admin:
      client:
        url:
        - http://localhost:9090/
server:
  port: 2222
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'