spring.application.name=webApp_Read_bookData-2


spring.datasource.username=root
spring.datasource.password=Pankaj@4321
spring.datasource.url=jdbc:mysql://localhost:3306/sbmsMvc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true