spring.application.name=dataJPA_2_databaseConnection

#==========================
# PRIMARY DATABASE
#==========================

spring.datasource.primary.jdbc-url=jdbc:mysql://localhost:3306/company_db
spring.datasource.primary.username=root
spring.datasource.primary.password=Pankaj@4321
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

#==========================
# SECONDARY DATABASE
#==========================

spring.datasource.secondary.jdbc-url=jdbc:mysql://localhost:3306/college_db
spring.datasource.secondary.username=root
spring.datasource.secondary.password=Pankaj@4321
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver

#==========================
# JPA
#==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true